queue_rules:
- name: default
  conditions:
  - status-success=version
  - status-success=specdown (ubuntu-latest)
  - status-success=specdown (macos-latest)
  - status-success=lint-markdown / lint-markdown
  - status-success=rust-checks / check
  - status-success=rust-checks / test (macos-latest)
  - status-success=rust-checks / test (ubuntu-latest)
  - status-success=rust-checks / test (windows-latest)
  - status-success=rust-checks / lints (macos-latest)
  - status-success=rust-checks / lints (ubuntu-latest)
  - status-success=rust-checks / lints (windows-latest)
  - status-success=rust-checks / security-audit

pull_request_rules:
- name: request review on external contributor
  conditions:
  - -author=PurpleBooth
  actions:
    assign:
      add_users:
      - PurpleBooth

- name: automatic rebase for dependencies
  conditions:
  - status-success=version
  - status-success=specdown (ubuntu-latest)
  - status-success=specdown (macos-latest)
  - status-success=lint-markdown / lint-markdown
  - status-success=rust-checks / check
  - status-success=rust-checks / test (macos-latest)
  - status-success=rust-checks / test (ubuntu-latest)
  - status-success=rust-checks / test (windows-latest)
  - status-success=rust-checks / lints (macos-latest)
  - status-success=rust-checks / lints (ubuntu-latest)
  - status-success=rust-checks / lints (windows-latest)
  - status-success=rust-checks / security-audit
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
