[package]
name = "git-moves-together"
version = "2.5.0"
edition = "2018"
categories = ["development-tools", "command-line-utilities"]
keywords = ["git", "coupling"]
repository = "https://github.com/PurpleBooth/git-moves-together"
description = "Find files that move at the same time in a git repository to identify coupling"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.23"
thiserror = "1.0.30"
clap = "3.0.0-beta.5"
comfy-table = "4.1.1"
tokio = { version = "1.12.0", features = ["full"] }
futures = "0.3.17"
miette = { version = "3.2.0", features = ["fancy"] }
time = "0.3.3"
[dev-dependencies]
tempfile = "3.2.0"
rand = "0.8.4"

[features]
