[package]
name = "git-moves-together"
version = "2.5.47"
edition = "2018"
categories = ["development-tools", "command-line-utilities"]
keywords = ["git", "coupling"]
repository = "https://github.com/PurpleBooth/git-moves-together"
description = "Find files that move at the same time in a git repository to identify coupling"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.16.0"
thiserror = "1.0.38"
clap = { version = "3.2.23", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode", "debug" ] }
comfy-table = "6.1.3"
tokio = { version = "1.24.1", features = ["full"] }
futures = "0.3.25"
miette = { version = "5.5.0", features = ["fancy"] }
time = "0.3.17"
[dev-dependencies]
tempfile = "3.3.0"
rand = "0.8.5"

[features]
