#!/usr/bin/env bash

set -euo pipefail

REPOSITORY_DIR="$PWD"
TEMPORARY_DIR="$(mktemp -d)/some-repo"
mkdir -p "$TEMPORARY_DIR"

if [[ -z "$(git config init.defaultBranch)" ]]; then
    git config --global init.defaultBranch main
fi

export GIT_COMMITTER_NAME=John Doe
export GIT_COMMITTER_EMAIL=john@doe.org
export GIT_AUTHOR_NAME=John Doe
export GIT_AUTHOR_EMAIL=john@doe.org
export PATH="$REPOSITORY_DIR/target/release/:$REPOSITORY_DIR/target/debug/:$PATH"
git -C "$TEMPORARY_DIR" init .
git -C "$TEMPORARY_DIR" config commit.gpgsign false
rm "$TEMPORARY_DIR/.git/hooks/"*
exec specdown run --running-dir "$TEMPORARY_DIR" "${@}"
